sudo: false
language: rust
rust:
  - stable
  - beta
  - nightly
before_script:
  - wget https://download.libsodium.org/libsodium/releases/libsodium-1.0.15.tar.gz
  - tar -xzvf libsodium-1.0.15.tar.gz
  - (cd libsodium-1.0.15 && ./configure --prefix=$HOME/.local && make && make install)
  - export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$HOME/.local/lib/pkgconfig
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/.local/lib
